### PR TITLE
Add macOS with Docker install instructions

### PR DESCRIPTION
**Pull request by jasoncpatton**
Still requires that users re-run Docker (via `run_htcondor_docker.sh`) to restart container, though that will change in the future.

### CODE REVIEW

**Comment by jasoncpatton** [comment]
When switching to the `macos_docker` branch on htpheno-cm, I get this in the log when I go to `/connect`:

```
[2020-06-24 16:49:04,767] [DEBUG] sources:22 ~ Will read user ID from request environment variable REMOTE_USER
[2020-06-24 16:49:04,767] [DEBUG] sources:26 ~ User ID is <me>
[2020-06-24 16:49:04,772] [ERROR] app:1423 ~ Exception on /connect [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/registration/registry/connect/views.py", line 22, in connect
    sources = get_sources(user_id)
  File "/var/www/registration/registry/sources.py", line 40, in get_sources
    entry["name"]: entry["sources"].split() for entry in parse_humans_file()
  File "/var/www/registration/registry/sources.py", line 40, in <dictcomp>
    entry["name"]: entry["sources"].split() for entry in parse_humans_file()
KeyError: 'sources'
```
I'm not sure why suddenly `get_sources` or `parse_humans_file` would suddenly stop working just because I added a new route in `views.py`.

**Comment by JoshKarpel** [comment]
It's because we have a human with no sources - latest commit to master fixes it, I recommend merging it.

**Comment by jasoncpatton** [comment]
> It's because we have a human with no sources - latest commit to master fixes it, I recommend merging it.

🤦 why I forget to merge master

**Review by JoshKarpel — APPROVED** [review]
LGTM; factored out some shared template code for displaying the install commands.

**Pull request merged**
